### ISSUE TITLE
QUAD web solver: order of presenting equations changes results

### ISSUE THREAD

**Issue by wasdmco** [alpertron/calculators#32] opened 2024-11-10 10:17 UTC
The web app probably is keeping some state between two solves, and this is affecting the result.
Example:
1. I try to solve the elliptical case as described on the METHODS page: $42x^2 + 8xy + 15y^2 + 23x + 17y - 4915 = 0$ ==> correct result $[x=-11,y=-1]$
2. now I try to  solve the hyperbolic equation I've described in #31 ==> doesn't find all the solutions
3. try to solve the elliptical equation again described in 1. above ==> no solutions
4. reload the webpage and try the same equation again ==> correct solution $[x = -11, y = -1]$

**Comment by wasdmco** [comment] 2024-11-10 10:34
Something interesting, maybe: when enabling teach, the first difference that is shown is this:
solver that works (pay attention to step 6):
![image](https://github.com/user-attachments/assets/7a077cbb-610a-47e5-8a7d-c49853478350)

solver that doesn't work (step 6 is failing now, but only in deciding that there are no convergents, even though (20) is the same in both cases)
![image](https://github.com/user-attachments/assets/0192d8f5-38b2-444a-a278-31930a5498a7)

**Comment by alpertron** [comment] 2024-11-10 13:28
Thanks for commenting about this error. It sounds like a variable not initialized, so the first time it works OK because its original value is zero, but the second time, the calculator does not work because that variable starts with an incorrect value.

**Comment by wasdmco** [comment] 2024-11-10 13:38
I don't know if it is due to the webapp, or if it would have the same problem directly from the C code. Is it possible that some C code has undefined behaviour, and that the undefined behaviour is not the same for native code and code translated to webasm ?

**Comment by alpertron** [comment] 2024-11-10 14:02
You could reproduce the problem by changing the file test.c and change the call to quadtext by several calls to quadtext changing the command line arguments by the actual coefficients that generate the problem. 

Something like:

quadText("42", "8", "15", "23", "17", "-4915");
quadText("26", "-91", "-26", "-58", "-59", "-71");
quadText("42", "8", "15", "23", "17", "-4915");

**Comment by wasdmco** [comment] 2024-11-10 21:50
You are right, I can reproduce it like that.
The issue is visible in quad.c::callbackQuadModElliptic, when computing the convergents. It turns out that ValL.sign is still 1 (which means negative) from the previous solve. Setting ValL.sign to 0 at the start of the function seems to resolve this issue, but I'm not sure if this is the right way. I couldn't find a function to initialize a BigInteger in bignbr.h.

**Comment by alpertron** [comment] 2024-11-10 22:00
Yes, I already found that error and now I'm testing the code. The square root function does not change the sign, so if that variable was negative, the convergents will be calculated wrongly, and you will never get solutions.

**Comment by wasdmco** [comment] 2024-11-10 22:08
great!
Unfortunately, this doesn't fix #31, that would have been cool :)

**Comment by alpertron** [comment] 2024-11-10 22:18
No, it does not fix the other issue. But notice that now, after all calls to function sqaureRoot, the BigInteger is marked as positive.

**Comment by alpertron** [comment] 2024-11-10 23:34
Please refresh the webpage so it reads 10 November 2024. Then try again.

**Comment by wasdmco** [comment] 2024-11-11 16:37
Hi Dario, looking good for me!

**Closed** 2024-11-11 16:39 UTC
